# Generated by Django 4.1.1 on 2022-11-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='试题id')),
                ('stems', models.TextField(blank=True, null=True, verbose_name='题干')),
                ('level', models.IntegerField(blank=True, choices=[(1, '选择题'), (2, '判断题'), (3, '填空题')], null=True, verbose_name='试题类型')),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
            },
        ),
        migrations.CreateModel(
            name='Testpaper',
            fields=[
                ('testpaper_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='试卷id')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='试卷名')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='TrueOrFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='标准答案')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectTestpaper.question', verbose_name='试题id')),
            ],
            options={
                'verbose_name': '判断题',
                'verbose_name_plural': '判断题',
            },
        ),
        migrations.CreateModel(
            name='TestpaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectTestpaper.question', verbose_name='试题id')),
                ('testpaper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectTestpaper.testpaper', verbose_name='试卷id')),
            ],
            options={
                'verbose_name': '试卷_试题',
                'verbose_name_plural': '试卷_试题',
            },
        ),
        migrations.CreateModel(
            name='Gapfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='标准答案')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectTestpaper.question', verbose_name='试题id')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(blank=True, max_length=80, null=True, verbose_name='选项A')),
                ('choice2', models.CharField(blank=True, max_length=80, null=True, verbose_name='选项B')),
                ('choice3', models.CharField(blank=True, max_length=80, null=True, verbose_name='选项C')),
                ('choice4', models.CharField(blank=True, max_length=80, null=True, verbose_name='选项D')),
                ('standard_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='标准答案')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectTestpaper.question', verbose_name='试题id')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
            },
        ),
    ]
