# Generated by Django 4.1.1 on 2022-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('consumer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consumer_account', models.CharField(blank=True, max_length=40, null=True)),
                ('consumer_name', models.CharField(blank=True, max_length=40, null=True)),
                ('consumer_password', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('number', models.CharField(blank=True, max_length=12, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('security_question', models.CharField(blank=True, max_length=255, null=True)),
                ('security_answer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
