# Generated by Django 4.2 on 2022-11-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollectTestpaper', '0003_alter_testpaper_hard'),
        ('Consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer_testPaper_first',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer.consumer', verbose_name='用户id')),
                ('testpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectTestpaper.testpaper', verbose_name='试卷id')),
            ],
            options={
                'verbose_name': '用户订阅',
                'verbose_name_plural': '用户订阅',
            },
        ),
    ]
