# Generated by Django 4.1.3 on 2022-11-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollectTestpaper', '0003_alter_testpaper_hard'),
        ('Consumer', '0002_consumer_testpaper_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer_answer_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户答案')),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer.consumer', verbose_name='用户id')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectTestpaper.question', verbose_name='试题id')),
                ('testpaper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollectTestpaper.testpaper', verbose_name='试卷id')),
            ],
            options={
                'verbose_name': '用户答题情况',
                'verbose_name_plural': '用户答题情况',
            },
        ),
    ]
